### ISSUE TITLE
求服务器端Linux运行

### ISSUE THREAD

**Issue by ChuJian2** [vhxubo/xxy-web#1]
老哥，这个怎么在服务器运行啊，能不能开发成就像这个一样https://github.com/YukiCoco/MoocFinder
谢谢老哥了。

**Comment by vhxubo** [comment]
## 搭建
```
// 拉取依赖
yarn install

// 编译
yarn build
```

编译后会生成 `dist` 文件夹，依次上传到网站指定目录下

Nginx 配置需要添加以下内容

```conf
location / {
    try_files $uri $uri/ /index.html;
}

location /api/
{
    proxy_pass  https://app.51xuexiaoyi.com;
}
```

## 参考链接
[HTML5 History 模式 | Vue Router](https://router.vuejs.org/zh/guide/essentials/history-mode.html#%E5%90%8E%E7%AB%AF%E9%85%8D%E7%BD%AE%E4%BE%8B%E5%AD%90)

**Comment by ChuJian2** [comment]
谢谢谢谢，我试试。
